DROP TABLE IF EXISTS answers;

CREATE TABLE answers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    model TEXT NOT NULL,
    wiki TEXT NOT NULL,
    gpt TEXT NOT NULL,
    correct INTEGER NOT NULL
);